repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-json
      - id: check-ast
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args: [--unsafe]
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: .+\.csv$
  - repo: https://github.com/tconbeer/sqlfmt
    rev: v0.21.1
    hooks:
      - id: sqlfmt
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: 'v1.88.0'
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
